source 'https://rubygems.org'

gem 'rake'
gem 'puppet'
gem 'puppet-lint', '2.0.0'
gem 'rspec-puppet'
gem 'beaker', '2.50.0'
gem 'beaker-rspec', '~> 5.0.0'
gem 'puppetlabs_spec_helper'
gem 'beaker-puppet_install_helper'
gem 'metadata-json-lint'
