source 'https://rubygems.org'

gem 'beaker'
gem 'beaker-puppet_install_helper'
gem 'beaker-rspec'
gem 'coveralls'
gem 'metadata-json-lint'
gem 'puppet'
gem 'puppet-lint'
gem 'puppetlabs_spec_helper'
gem 'rake'
gem 'rspec-puppet'
gem 'rubocop-rspec'
