source 'https://rubygems.org'

gem 'rake'
gem 'puppet'
gem 'puppet-lint'
gem 'rspec-puppet'
gem 'beaker', :git => 'https://github.com/spjmurray/beaker', :branch => 'beaker_stable'
gem 'beaker-rspec'
gem 'puppetlabs_spec_helper'
gem 'beaker-puppet_install_helper'
gem 'metadata-json-lint'
gem 'rubocop-rspec'
